import globalStateManager from "./globalState.js";
import slimeGlobalStateManager from "./slimeGlobalState.js";
import oldmanGlobalStateManager from "./oldmanGlobalState.js";
import lumberjackGlobalStateManager from "./lumberjackGlobalState.js";
import playerGlobalStateManager from "./playerGlobalState.js";
import shopkeeperGlobalStateManager from "./shopkeeperGlobalState.js";
import prisonerGlobalStateManager from "./prisonerGlobalState.js";
import wizardGlobalStateManager from "./wizardGlobalState.js";
import guardGlobalStateManager from "./guardGlobalState.js";
import farmerGlobalStateManager from "./farmerGlobalState.js";
import chickenGlobalStateManager from "./chickenGlobalState.js";
import bartenderGlobalStateManager from "./bartenderGlobalState.js";
import frogGlobalStateManager from "./frogGlobalState.js";
import hatguyGlobalStateManager from "./hatguyGlobalState.js";
import cowGlobalStateManager from "./cowGlobalState.js";
import gardenerGlobalStateManager from "./gardenerGlobalState.js";
import beanStalkGlobalStateManager from "./beanStalkGlobalState.js";
import batGlobalStateManager from "./batGlobalState.js";
import swordsmanGlobalStateManager from "./swordsmanGlobalState.js";
import drunkardGlobalStateManager from "./drunkardGlobalState.js";

export const gameState = globalStateManager().getInstance();
export const slimeState = slimeGlobalStateManager().getInstance();
export const oldmanState = oldmanGlobalStateManager().getInstance();
export const lumberjackState = lumberjackGlobalStateManager().getInstance();
export const playerState = playerGlobalStateManager().getInstance();
export const shopkeeperState = shopkeeperGlobalStateManager().getInstance();
export const prisonerState = prisonerGlobalStateManager().getInstance();
export const wizardState = wizardGlobalStateManager().getInstance();
export const guardState = guardGlobalStateManager().getInstance();
export const farmerState = farmerGlobalStateManager().getInstance();
export const chickenState = chickenGlobalStateManager().getInstance();
export const bartenderState = bartenderGlobalStateManager().getInstance();
export const frogState = frogGlobalStateManager().getInstance();
export const hatguyState = hatguyGlobalStateManager().getInstance();
export const cowState = cowGlobalStateManager().getInstance();
export const gardenerState = gardenerGlobalStateManager().getInstance();
export const beanStalkState = beanStalkGlobalStateManager().getInstance();
export const batState = batGlobalStateManager().getInstance();
export const swordsmanState = swordsmanGlobalStateManager().getInstance();
export const drunkardState = drunkardGlobalStateManager().getInstance();