name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Debug and create config.js
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        echo "=================== FULL DEBUG ==================="
        echo "Step 1: Check if GEMINI_API_KEY exists"
        if [ -z "$GEMINI_API_KEY" ]; then
          echo "❌ GEMINI_API_KEY is empty or not set"
        else
          echo "✅ GEMINI_API_KEY exists"
          echo "Length: ${#GEMINI_API_KEY}"
          echo "First 10 chars: ${GEMINI_API_KEY:0:10}"
        fi
        
        echo "Step 2: Check current directory"
        pwd
        ls -la
        
        echo "Step 3: Remove any existing config.js"
        rm -f config.js
        
        echo "Step 4: Create config.js with placeholders"
        cat > config.js << 'CONFIGEOF'
        // Generated by GitHub Actions
        window.CONFIG = {
          GEMINI_API_KEY: 'PLACEHOLDER_API_KEY',
          DEPLOY_VERSION: 'PLACEHOLDER_DATE',
          BUILD_ID: 'PLACEHOLDER_BUILD'
        };
        CONFIGEOF
        
        echo "Step 5: Verify config.js was created"
        if [ -f config.js ]; then
          echo "✅ config.js created successfully"
          echo "File size: $(wc -c < config.js) bytes"
          echo "Content before replacement:"
          cat config.js
        else
          echo "❌ config.js was NOT created"
          exit 1
        fi
        
        echo "Step 6: Replace placeholders"
        sed -i "s/PLACEHOLDER_API_KEY/${GEMINI_API_KEY}/g" config.js
        sed -i "s/PLACEHOLDER_DATE/$(date +"%Y-%m-%d %H:%M:%S UTC")/g" config.js
        sed -i "s/PLACEHOLDER_BUILD/$(echo $GITHUB_SHA | head -c 8)/g" config.js
        
        echo "Step 7: Verify replacements worked"
        echo "=== FINAL CONFIG.JS ==="
        cat config.js
        echo "======================="
        
        echo "Step 8: Check if API key was inserted"
        if grep -q "AIzaSy" config.js; then
          echo "✅ API key successfully inserted"
        else
          echo "❌ API key NOT found in final config.js"
          if [ -z "$GEMINI_API_KEY" ]; then
            echo "Reason: GEMINI_API_KEY environment variable is empty"
          else
            echo "Reason: sed replacement may have failed"
            echo "GEMINI_API_KEY value: ${GEMINI_API_KEY}"
          fi
        fi
        
        echo "Step 9: List all files to be uploaded"
        ls -la
        echo "================= END DEBUG =================="
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
